apiVersion: v2
name: rtdmsfilereporter
description: Micro service dedicated to retrieve and keep updated the file report for senders. It implements the CQRS pattern.
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 2.0.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"